import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#1e47f3",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad5",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-on-surface": "#f2f1ec",
        "on-tertiary-fixed-variant": "#005235",
        "surface-container-high": "#e9e8e3",
        secondary: "#3d3d3d",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#474646",
        "primary-fixed": "#dee0ff",
        primary: "#0037e4",
        "on-tertiary-container": "#9affca",
        "surface-container-low": "#f5f4ef",
        "tertiary-fixed": "#8df7c1",
        "on-secondary-container": "#656464",
        "on-error-container": "#93000a",
        "on-surface": "#1b1c19",
        "primary-fixed-dim": "#bac3ff",
        "outline-variant": "#c4c5d9",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e5e2e1",
        "tertiary-fixed-dim": "#71dba6",
        "on-error": "#ffffff",
        surface: "#faf9f4",
        "on-primary-fixed-variant": "#002fc8",
        "on-secondary": "#ffffff",
        "inverse-surface": "#30312e",
        "on-surface-variant": "#444656",
        background: "#faf9f4",
        "primary-container": "#3155ff",
        "on-background": "#1b1c19",
        outline: "#525464",
        "on-tertiary-fixed": "#002113",
        "tertiary-container": "#007950",
        "on-tertiary": "#ffffff",
        tertiary: "#005e3d",
        "on-primary-container": "#e9e9ff",
        "inverse-primary": "#bac3ff",
        "on-primary-fixed": "#00105b",
        "surface-container-highest": "#e3e3de",
        "surface-bright": "#faf9f4",
        error: "#ba1a1a",
        "secondary-fixed": "#e5e2e1",
        "surface-container": "#efeee9",
        "error-container": "#ffdad6",
        "surface-variant": "#e3e3de",
        // Semantic shortcuts
        ink: "#1b1c19",
        canvas: "#f5f4ef",
        "electric-blue": "#3155ff",
        emerald: "#00875A",
        amber: "#D97706",
        crimson: "#DC2626",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        "unit-1": "0.25rem",
        "unit-2": "0.5rem",
        "unit-3": "0.75rem",
        "unit-4": "1rem",
        "unit-5": "1.25rem",
        "unit-6": "1.5rem",
        "unit-8": "2rem",
        "unit-10": "2.5rem",
        "unit-12": "3rem",
        "unit-16": "4rem",
        "gutter-mobile": "0.75rem",
        "gutter-desktop": "1.25rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "num-display": ["Inter", "sans-serif"],
        "num-headline": ["Inter", "sans-serif"],
        "num-table": ["Inter", "sans-serif"],
        "code-md": ["'JetBrains Mono'", "monospace"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          {
            lineHeight: "52px",
            letterSpacing: "-0.04em",
            fontWeight: "700",
          },
        ],
        "display-lg-mobile": [
          "32px",
          {
            lineHeight: "38px",
            letterSpacing: "-0.03em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "38px",
            letterSpacing: "-0.03em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "24px",
          {
            lineHeight: "30px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "22px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-sm": [
          "18px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "16px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
        "body-sm": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.01em",
            fontWeight: "400",
          },
        ],
        "num-display": [
          "36px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.03em",
            fontWeight: "700",
          },
        ],
        "num-headline": [
          "24px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "num-table": [
          "13px",
          {
            lineHeight: "18px",
            letterSpacing: "0em",
            fontWeight: "600",
          },
        ],
        "code-md": [
          "13px",
          {
            lineHeight: "18px",
            letterSpacing: "-0.01em",
            fontWeight: "500",
          },
        ],
        "code-sm": [
          "11px",
          {
            lineHeight: "14px",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "label-caps": [
          "10px",
          {
            lineHeight: "12px",
            letterSpacing: "0.08em",
            fontWeight: "600",
          },
        ],
      },
      boxShadow: {
        neo: "2px 2px 0px #1b1c19",
        "neo-lg": "4px 4px 0px #1b1c19",
        "neo-sm": "1px 1px 0px #1b1c19",
        "neo-blue": "2px 2px 0px #3155ff",
        "neo-sidebar": "2px 0px 0px #1b1c19",
        "neo-topbar": "0px 2px 0px #1b1c19",
        none: "none",
      },
    },
  },
  plugins: [],
};
export default config;
