import Link from "next/link";
import { ArrowRight, RefreshCw } from "lucide-react";
import StatusBadge from "@/components/ui/StatusBadge";
import { indexLiveAgreements } from "@/lib/server/live-ledger";
import { REGISTRY_STATES } from "@/lib/server/public-status";

export const dynamic = "force-dynamic";

export default async function AgreementsPage() {
  let index: Awaited<ReturnType<typeof indexLiveAgreements>> | null = null;
  try { index = await indexLiveAgreements(); } catch { index = null; }
  return <div className="space-y-unit-6">
    <section className="flex flex-col justify-between gap-unit-4 border-b-2 border-on-surface pb-unit-5 md:flex-row md:items-end"><div><span className="bg-on-surface px-unit-2 py-0.5 font-label-caps font-bold text-label-caps tracking-widest text-surface-container-lowest">AGREEMENT LEDGER</span><h1 className="mt-2 font-headline-lg font-bold tracking-tight text-headline-lg text-on-surface">Agreements</h1><p className="mt-1 max-w-2xl font-body-md text-body-md text-secondary">Discovered from finalized AgreementOpened events, then verified against Sepolia registry and Arc escrow state.</p></div><div className="neo-shadow border border-on-surface bg-surface-container-lowest px-unit-4 py-unit-2"><div className="font-label-caps font-bold text-label-caps text-secondary">INDEXED RECORDS</div><div className="font-code-md font-bold text-primary">{index ? index.agreements.length.toString().padStart(2, "0") : "00"}</div></div></section>
    {index ? <section className="border-2 border-on-surface bg-surface-container-lowest p-unit-4 neo-shadow"><p className="font-label-caps font-bold text-label-caps">FINALIZED INDEX WINDOW</p><p className="mt-2 font-code-sm">{index.fromBlock.toString()} → {index.toBlock.toString()}</p><p className="mt-2 font-body-md text-body-md text-secondary">{index.truncated ? "Recent finalized blocks are indexed by default. Set AGREEMENT_INDEX_START_BLOCK to reconcile a wider history." : "Configured history range fully reconciled."}</p></section> : null}
    {index && index.agreements.length > 0 ? <section className="neo-shadow-lg overflow-x-auto border-2 border-on-surface bg-surface-container-lowest"><table className="w-full border-collapse text-left"><thead><tr className="border-b-2 border-on-surface bg-surface-container font-label-caps text-label-caps text-secondary"><th className="px-unit-4 py-unit-3">Agreement ID</th><th className="px-unit-4 py-unit-3">Counterparty</th><th className="px-unit-4 py-unit-3">Capital</th><th className="px-unit-4 py-unit-3">Yield</th><th className="px-unit-4 py-unit-3">State</th><th className="px-unit-4 py-unit-3 text-right">Action</th></tr></thead><tbody>{index.agreements.map((agreement) => <tr key={agreement.id} className="border-b border-surface-container-highest font-body-sm text-body-sm"><td className="break-all px-unit-4 py-unit-4 font-code-sm">{agreement.id}</td><td className="break-all px-unit-4 py-unit-4 font-code-sm text-primary">{agreement.counterparty === "0x0000000000000000000000000000000000000000" ? "Awaiting counterparty" : agreement.counterparty}</td><td className="px-unit-4 py-unit-4 font-code-md font-bold">{agreement.capital > 0n ? `${(Number(agreement.capital) / 1_000_000).toLocaleString()} USDC` : "Pending terms"}</td><td className="px-unit-4 py-unit-4 font-code-md font-bold text-tertiary">{agreement.yieldBps > 0n ? `${(Number(agreement.yieldBps) / 100).toFixed(2)}% APR` : "Pending terms"}</td><td className="px-unit-4 py-unit-4"><StatusBadge status={REGISTRY_STATES[agreement.registryState] ?? "UNKNOWN"} /></td><td className="px-unit-4 py-unit-4 text-right"><Link href={`/agreements/${agreement.id}`} className="inline-flex items-center gap-1 border border-on-surface px-unit-3 py-1 font-code-sm font-bold">INSPECT <ArrowRight size={14} aria-hidden="true" /></Link></td></tr>)}</tbody></table></section> : <section className="border-2 border-on-surface bg-surface-container-lowest p-unit-6"><RefreshCw size={18} /><h2 className="mt-2 font-headline-sm font-bold">{index ? "No agreements in index window" : "Live agreement index unavailable"}</h2><p className="mt-2 text-secondary">{index ? "No AgreementOpened event was found in the configured finalized block range." : "The finalized RPC provider could not be queried. No substitute data is displayed."}</p></section>}
  </div>;
}
