import Link from "next/link";
import { Activity, ArrowRight, Bot, Cpu } from "lucide-react";
import canonical from "../../../../deployments/canonical.json";
import { readLiveAgreement } from "@/lib/server/live-ledger";
import { REGISTRY_STATES } from "@/lib/server/public-status";

export const dynamic = "force-dynamic";

export default async function AgentsPage() {
  let agreement: Awaited<ReturnType<typeof readLiveAgreement>> | null = null;
  try { agreement = await readLiveAgreement(canonical.rehearsal.agreementId as `0x${string}`); } catch { agreement = null; }
  const agents = agreement ? [{ name: "Treasury Agent", role: "Principal / proposer", address: agreement.principal, capacity: agreement.capital }, { name: "Strategy Agent", role: "Counterparty", address: agreement.counterparty, capacity: agreement.capital }] : [];
  return <div className="space-y-unit-6"><section className="flex flex-col md:flex-row md:items-end justify-between border-b-2 border-on-surface pb-unit-5 gap-unit-4"><div><span className="font-label-caps text-label-caps bg-on-surface text-surface-container-lowest px-unit-2 py-0.5 tracking-widest font-bold">LIVE ACTORS</span><h1 className="font-headline-lg text-headline-lg font-bold text-on-surface tracking-tight mt-2">Agents Directory</h1><p className="font-body-md text-body-md text-secondary mt-1">Agent identities and agreement relationships read from the public registry.</p></div><div className="border border-on-surface bg-surface-container-lowest px-unit-4 py-unit-2 neo-shadow"><div className="font-label-caps text-label-caps text-secondary font-bold">IDENTITIES READ</div><div className="font-code-md text-code-md font-bold text-primary">{agents.length.toString().padStart(2, "0")}</div></div></section>{agreement ? <section className="grid grid-cols-1 xl:grid-cols-2 gap-unit-6">{agents.map((agent) => <article key={agent.address} className="bg-surface-container-lowest border-2 border-on-surface neo-shadow-lg"><header className="bg-surface-container-high border-b-2 border-on-surface p-unit-6"><div className="flex justify-between items-start gap-4"><div className="flex items-center gap-unit-4"><div className="w-14 h-14 bg-on-surface text-white flex items-center justify-center font-headline-sm font-bold"><Bot /></div><div><h2 className="font-headline-sm font-bold">{agent.name}</h2><div className="font-code-sm text-primary">{agent.role}</div></div></div><span className="font-label-caps border border-on-surface px-2 py-1">{REGISTRY_STATES[agreement.registryState]}</span></div><div className="mt-4 border border-on-surface bg-white p-3 font-code-sm break-all"><span className="text-secondary">IDENTITY · </span>{agent.address}</div></header><div className="p-unit-6 grid grid-cols-2 gap-4 font-code-sm"><div><div className="font-label-caps text-secondary">CAPITAL BOUND</div><strong>{(Number(agent.capacity) / 1_000_000).toLocaleString()} USDC</strong></div><div><div className="font-label-caps text-secondary">EVIDENCE</div><strong className="inline-flex items-center gap-1"><Cpu size={14} /> EIP-712 terms</strong></div></div><footer className="border-t-2 border-on-surface bg-surface-container-low p-4 flex justify-between items-center font-code-sm"><span className="inline-flex items-center gap-2"><Activity size={15} /> Registry participant</span><Link href={`/agreements/${agreement.id}`} className="inline-flex items-center gap-1 font-bold">VIEW AGREEMENT <ArrowRight size={14} /></Link></footer></article>)}</section> : <section className="border-2 border-on-surface bg-surface-container-lowest p-unit-6"><h2 className="font-headline-sm font-bold">No finalized agent identities available</h2><p className="text-secondary mt-2">The deployed agreement could not be read from both configured chains. No fixture identities are displayed.</p></section>}</div>;
}
